// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ONUBT5-3kSG_nGO5O_jsVqykwKcvUWI',
    appId: '1:547314015747:web:4381256938f6b38aa57836',
    messagingSenderId: '547314015747',
    projectId: 'ecommerce-app-a60e6',
    authDomain: 'ecommerce-app-a60e6.firebaseapp.com',
    storageBucket: 'ecommerce-app-a60e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfwoXuuHm7Df-YkoHsK-lcsrqUyAzVBF8',
    appId: '1:547314015747:android:5d73b4e2fd1e7663a57836',
    messagingSenderId: '547314015747',
    projectId: 'ecommerce-app-a60e6',
    storageBucket: 'ecommerce-app-a60e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzuVzwhiDjvSsUyo2Y1XaIG1cEWXpTTs',
    appId: '1:547314015747:ios:fb05c6ac6fbd073ca57836',
    messagingSenderId: '547314015747',
    projectId: 'ecommerce-app-a60e6',
    storageBucket: 'ecommerce-app-a60e6.firebasestorage.app',
    iosBundleId: 'com.example.eommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzuVzwhiDjvSsUyo2Y1XaIG1cEWXpTTs',
    appId: '1:547314015747:ios:fb05c6ac6fbd073ca57836',
    messagingSenderId: '547314015747',
    projectId: 'ecommerce-app-a60e6',
    storageBucket: 'ecommerce-app-a60e6.firebasestorage.app',
    iosBundleId: 'com.example.eommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ONUBT5-3kSG_nGO5O_jsVqykwKcvUWI',
    appId: '1:547314015747:web:5162dd596cde1b1ea57836',
    messagingSenderId: '547314015747',
    projectId: 'ecommerce-app-a60e6',
    authDomain: 'ecommerce-app-a60e6.firebaseapp.com',
    storageBucket: 'ecommerce-app-a60e6.firebasestorage.app',
  );
}
